version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - node --version
      - npm --version
  
  pre_build:
    commands:
      - echo "Running pre-build commands..."
      - npm install
  
  build:
    commands:
      - echo "Running build commands..."
      - npm run test
      - echo "Build completed successfully!"
  
  post_build:
    commands:
      - echo "Running post-build commands..."
      - echo "Application ready for deployment"

artifacts:
  files:
    - '**/*'
  base-directory: '.'